name: PlotPlugin
version: 1.0
main: com.yourname.plotplugin.PlotPlugin
api-version: 1.21
commands:
  work:
    description: Work to earn money
  business:
    description: Create a business
  pay:
    description: Pay another player or business
  createplot:
    description: Creates a 22x22 plot with a sign
    usage: /<command> <plotID>
    permission: plotplugin.createplot
  buyplot:
    description: Allows a player to buy a plot
    usage: /<command> <plotID>
    permission: plotplugin.buyplot
  addeditor:
    description: Adds an editor to a plot
    usage: /<command> <plotID> <playerName>
    permission: plotplugin.addeditor
  towntp:
    description: Teleports a player to a specified town from the config file
    usage: /<command> <townName>
    permission: plotplugin.towntp